const catalog = {
  departments: [
    {
      id: "CSE",
      name: "Department of Computer Science and Engineering",
      programmes: [
        { programme: "Bachelor of Technology", branch: "Computer Science & Engineering" },
        { programme: "Bachelor of Technology", branch: "Data Science and Artificial Intelligence" },
        { programme: "Bachelor of Technology", branch: "Cloud Computing and Artificial Intelligence" },
        { programme: "Bachelor of Technology", branch: "Artificial Intelligence and Machine Learning" },
        { programme: "Bachelor of Technology", branch: "Cyber Security & Artificial Intelligence" },
        { programme: "Master of Technology", branch: "Computer Science & Engineering" },
        { programme: "Master of Technology", branch: "Advanced Computing and Data Science" },
        { programme: "Doctor of Philosophy", branch: "Computer Science & Engineering" },
        { programme: "Master of Technology", branch: "Robotics and Artificial Intelligence" }
      ]
    }
  ],
  theoryCourses: [
    { code: "PY101", name: "Physics", year: 1, departmentId: "CSE" },
    { code: "EE103", name: "Basic Electrical Engg", year: 1, departmentId: "CSE" },
    { code: "LN132", name: "Communication Skills: Theory and Practices", year: 1, departmentId: "CSE" },
    { code: "MT149", name: "Mathematics-I for Computer Science & Engineering", year: 1, departmentId: "CSE" },
    { code: "HM101", name: "RASHTRA GAURAV", year: 1, departmentId: "CSE" },
    { code: "EC102", name: "Switching theory and logic design", year: 1, departmentId: "CSE" },
    { code: "CS101", name: "Computer Programming", year: 1, departmentId: "CSE" },
    { code: "ES102", name: "Concept of Environmental Studies", year: 1, departmentId: "CSE" },
    { code: "ME101", name: "Basic Mechanical Engineering", year: 1, departmentId: "CSE" },
    { code: "MT150", name: "Mathematics-II for Computer Science & Engineering", year: 1, departmentId: "CSE" },
    { code: "CS204", name: "Data Structure Using C", year: 2, departmentId: "CSE" },
    { code: "CS270", name: "Object Oriented Concepts using JAVA", year: 2, departmentId: "CSE" },
    { code: "CS229", name: "Software Engineering", year: 2, departmentId: "CSE" },
    { code: "CS206", name: "Discrete Structure", year: 2, departmentId: "CSE" },
    { code: "CS203", name: "Cyber Law and Information Security", year: 2, departmentId: "CSE" },
    { code: "CS303", name: "Principles of Operating System", year: 2, departmentId: "CSE" },
    { code: "CS212", name: "Database Management System", year: 2, departmentId: "CSE" },
    { code: "CS290", name: "Full Stack Development- Front End", year: 2, departmentId: "CSE" },
    { code: "CS236", name: "Computer Organization & Microprocessor", year: 2, departmentId: "CSE" },
    { code: "MT238", name: "Mathematical Analysis for Computer Science & Engineering", year: 2, departmentId: "CSE" },
    { code: "BM226", name: "Human Values & Professional Ethics", year: 2, departmentId: "CSE" },
    { code: "BM225", name: "Principles of Management and Engineering Economics", year: 2, departmentId: "CSE" },
    { code: "ES202", name: "Disasters, Management", year: 2, departmentId: "CSE" },
    { code: "CS301", name: "Design and Analysis of Algorithm", year: 3, departmentId: "CSE" },
    { code: "CS-303", name: "Principles of Operating System", year: 3, departmentId: "CSE" },
    { code: "CS311", name: "Software Project & Quality Management", year: 3, departmentId: "CSE" },
    { code: "CS312", name: "Digital Image Processing", year: 3, departmentId: "CSE" },
    { code: "CS336", name: "Full Stack Development- Backend", year: 3, departmentId: "CSE" },
    { code: "CS339", name: "Introduction to Artificial Intelligence", year: 3, departmentId: "CSE" },
    { code: "CS341", name: "Introduction to Internet of Things", year: 3, departmentId: "CSE" },
    { code: "CS342", name: "Data Compression", year: 3, departmentId: "CSE" },
    { code: "CS334", name: "Cloud Computing", year: 3, departmentId: "CSE" },
    { code: "CS305", name: "Computer Networks", year: 3, departmentId: "CSE" },
    { code: "CS313", name: "Microprocessor and its Applications", year: 3, departmentId: "CSE" },
    { code: "CS315", name: "Compiler Design", year: 3, departmentId: "CSE" },
    { code: "CS320", name: "Real Time Systems", year: 3, departmentId: "CSE" },
    { code: "CS346", name: "Concepts in Advanced Database System", year: 3, departmentId: "CSE" },
    { code: "CS347", name: "Green Computing", year: 3, departmentId: "CSE" },
    { code: "CS348", name: "Human Computer Interaction", year: 3, departmentId: "CSE" },
    { code: "CS425", name: "Introduction to Machine Learning", year: 4, departmentId: "CSE" },
    { code: "CS410", name: "Distributed Systems", year: 4, departmentId: "CSE" },
    { code: "CS412", name: "Cryptography and Network Security", year: 4, departmentId: "CSE" },
    { code: "CS415", name: "Fuzzy Logic & Neural Networks", year: 4, departmentId: "CSE" },
    { code: "CS417", name: "Mobile Computing", year: 4, departmentId: "CSE" },
    { code: "CS418", name: "Data Warehouse and Data Mining", year: 4, departmentId: "CSE" },
    { code: "CS419", name: "Pattern Recognition", year: 4, departmentId: "CSE" }
  ],
  practicalCourses: [
    { code: "CS131", name: "Web Design Lab", year: 1, departmentId: "CSE" },
    { code: "ME103", name: "Engineering Graphics", year: 1, departmentId: "CSE" },
    { code: "CS289", name: "Web Scripting Lab", year: 2, departmentId: "CSE" },
    { code: "CS272", name: "Python Programming Lab", year: 2, departmentId: "CSE" },
    { code: "CS282", name: "Advance Java Programming Lab", year: 2, departmentId: "CSE" },
    { code: "CS302", name: "Design and Analysis of Algorithm Lab", year: 3, departmentId: "CSE" },
    { code: "CS337", name: "Full Stack Development- Backend Lab", year: 3, departmentId: "CSE" },
    { code: "CS338", name: "Mobile App Development Lab", year: 3, departmentId: "CSE" },
    { code: "CS300", name: "Industrial Training/ internship/Apprentices -II", year: 3, departmentId: "CSE" },
    { code: "CS306", name: "Computer Networks Lab", year: 3, departmentId: "CSE" },
    { code: "CS314", name: "Microprocessor Lab", year: 3, departmentId: "CSE" },
    { code: "CS316", name: "Compiler Design Lab", year: 3, departmentId: "CSE" },
    { code: "CS421", name: "Minor Project", year: 4, departmentId: "CSE" },
    { code: "CS424", name: "SciLab", year: 4, departmentId: "CSE" },
    { code: "CS426", name: "Competitive Coding", year: 4, departmentId: "CSE" },
    { code: "CS499", name: "Major Project", year: 4, departmentId: "CSE" }
  ],
  faculty: [
    { id: "FAC_CSE_001", name: "Dr. Shish Ahmad", designation: "Professor", departmentId: "CSE" },
    { id: "FAC_CSE_002", name: "Dr. Mohammad Haroon", designation: "Professor", departmentId: "CSE" },
    { id: "FAC_CSE_003", name: "Dr. Manish Madhava Tripathi", designation: "Professor", departmentId: "CSE" },
    { id: "FAC_CSE_004", name: "Mrs. Kavita Agarwal", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_005", name: "Dr. Jameel Ahmad", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_006", name: "Dr. Halima Sadia", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_007", name: "Dr. Faiyaz Ahamad", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_008", name: "Dr. Sheeba Praveen", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_009", name: "Dr. Mohammad Akbar", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_010", name: "Dr. Mohammad Suaib", designation: "Associate Professor", departmentId: "CSE" },
    { id: "FAC_CSE_011", name: "Dr. Mohd Usman Khan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_012", name: "Dr. Roshan Jahan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_013", name: "Mr. Rahul Ranjan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_014", name: "Dr. Ankita Srivastava", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_015", name: "Dr. Nudrat Fatima", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_016", name: "Dr. Sifatullah Siddiqi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_017", name: "Dr. S. H. Abbas Rizvi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_018", name: "Mrs. Saleha Mariyam", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_019", name: "Mr. Aaftab Alam", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_020", name: "Mr. Ehteshaam Hussain", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_021", name: "Mr. Mohammad Aalam Khan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_022", name: "Dr. Anum Kamal", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_023", name: "Ms. Nida Khan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_024", name: "Ms. Falak Alam", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_025", name: "Ms. Ambreen Anees", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_026", name: "Mr. Anas Habib Zuberi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_027", name: "Ms. Ummey Habiba", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_028", name: "Ms. Mariyam Kidwai", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_029", name: "Noorishta Hashmi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_030", name: "Mr. Pervez Rauf", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_031", name: "Mr. Danish Ahmad", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_032", name: "Mr. Ajaz Husain Warsi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_033", name: "Ms. Shra Fatima", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_034", name: "Mr. Faizan Ahmad", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_035", name: "Ms. Naziya Anjum", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_036", name: "Mr. Pushpendra Dwivedi", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_037", name: "Dr. Raziqa Masood", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_038", name: "Mr. Balmukund Maurya", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_039", name: "Ms. Tabassum", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_040", name: "Ms. Mariyam Fatima", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_041", name: "Ms. Hina Parveen", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_042", name: "Ms. Saman Khan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_043", name: "Zainab Khan", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_044", name: "Aqsa Fatima", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_045", name: "Shaba Irram", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_046", name: "Azra Iftekhar", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_047", name: "Yusra Beg", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_048", name: "Abrarul Haque Siddique", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_049", name: "Minhajul Arfeen", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_050", name: "Amina Bano", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_051", name: "Falak Khursheed", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_052", name: "Umar Badr Shafeeque", designation: "Assistant Professor", departmentId: "CSE" },
    { id: "FAC_CSE_053", name: "Obaidullah", designation: "Assistant Professor", departmentId: "CSE" }
  ],
  labInstructors: [
    { id: "LAB_CSE_001", name: "Mr. Riyazuddin Khan", designation: "Senior Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_002", name: "Mrs. Nida Khan", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_003", name: "Mr. Shoeb Ahad Siddiqui", designation: "Senior Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_004", name: "Mr. Badaruzzaman", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_005", name: "Mr. Mohammad Ishaque", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_006", name: "Ms. Mariam Daud", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_007", name: "Ms. Qudsia Shahab", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_008", name: "Mr. Abhijeet Shukla", designation: "Senior Lab Instructor", departmentId: "CSE" },
    { id: "LAB_CSE_009", name: "Mr. Monis Farooqui", designation: "Senior Lab Instructor", departmentId: "CSE" }
  ]
};